# Generated by Django 4.2.7 on 2023-11-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durin', '0003_alter_client_token_ttl'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authtoken',
            name='unique token for user per client',
        ),
    ]
